# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_linux
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_linux)
  PicturaFramework_config = debug_linux
  PicturaDemo_config = debug_linux

else ifeq ($(config),release_linux)
  PicturaFramework_config = release_linux
  PicturaDemo_config = release_linux

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := PicturaFramework PicturaDemo

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

PicturaFramework:
ifneq (,$(PicturaFramework_config))
	@echo "==== Building PicturaFramework ($(PicturaFramework_config)) ===="
	@${MAKE} --no-print-directory -C Sources -f Makefile config=$(PicturaFramework_config)
endif

PicturaDemo: PicturaFramework
ifneq (,$(PicturaDemo_config))
	@echo "==== Building PicturaDemo ($(PicturaDemo_config)) ===="
	@${MAKE} --no-print-directory -C Examples/PicturaDemo/Sources -f Makefile config=$(PicturaDemo_config)
endif

clean:
	@${MAKE} --no-print-directory -C Sources -f Makefile clean
	@${MAKE} --no-print-directory -C Examples/PicturaDemo/Sources -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_linux"
	@echo "  release_linux"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   PicturaFramework"
	@echo "   PicturaDemo"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"